<a href="https://colab.research.google.com/github/w-olivine29/data-analysis/blob/main/%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_6%EA%B0%95_%EC%8B%A4%EC%8A%B5_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%A0%84%EC%B2%98%EB%A6%AC1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 오픈소스 기반 데이터 분석 6강 - 데이터 전처리 1

### 참고
df[], df.loc[]
->  대괄호를 사용했다고 df, df.loc 가 리스트라는 뜻이 아님

파이썬에서는 어떤 객체 뒤에 대괄호 []를 붙이면, 파이썬 내부에서  __getitem__()이라는 메서드를 대신 호출하도록 약속되어 있음

### 6-1 데이터 훑어보기

In [4]:
import pandas as pd
import numpy as np

data = {
    'name': ['김민수', '이지영', '박준호', '최서연', '정도윤'],
    'age': [25, 30, 28, 22, 35],
    'city': ['서울', '부산', '인천', '서울', '대전'],
    'score': [90, 85, 95, 80, np.nan]
}
df = pd.DataFrame(data)

# 데이터 측정
df.describe() # 기본설정은 수치형 데이터만 나옴


# 모든 데이터 타입 측정
df.describe(include= "all") # 범주형 데이터도 포함하기 위해 설정

# 수치형 데이터 측정
df.describe(include= [np.number])

# 범주형 데이터 측정
df.describe(include= ["object"])

# 특정 열 분석
df["score"].describe()

count     4.000000
mean     87.500000
std       6.454972
min      80.000000
25%      83.750000
50%      87.500000
75%      91.250000
max      95.000000
Name: score, dtype: float64

### 6-2 DataFrame 열 선택 및 **조작**

In [15]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}
df = pd.DataFrame(data)

# 특정 열 선택
selected_col = df[["이름", "학과", "학점"]]
print(selected_col, end="\n\n")

# DataFrame 열순서 변경 (원하는 순서로 나열 가능)
reordered_cols = df[["학과", "학년", "이름", "학점"]]
print(reordered_cols, end="\n\n")

# DataFrame 열이름 변경
renamed_cols = df.rename(columns={"이름": "학생명", "학점": "평점"})
print(renamed_cols, end="\n\n")

    이름     학과   학점
0  김철수  컴퓨터공학  4.2
1  이영희    경영학  3.8
2  박민수   전자공학  4.5
3  최지훈     의학  3.9
4  정소희    심리학  3.5

      학과  학년   이름   학점
0  컴퓨터공학   1  김철수  4.2
1    경영학   2  이영희  3.8
2   전자공학   3  박민수  4.5
3     의학   4  최지훈  3.9
4    심리학   2  정소희  3.5

   학생명  학년   평점     학과    동아리
0  김철수   1  4.2  컴퓨터공학  프로그래밍
1  이영희   2  3.8    경영학   독서토론
2  박민수   3  4.5   전자공학   로봇공학
3  최지훈   4  3.9     의학   봉사활동
4  정소희   2  3.5    심리학   음악감상

### 6-3 DataFrame 행 선택

In [65]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"],
}

# ==============================================================================
# 1. 기본 생성 및 인덱스(인덱스 라벨) 설정
# ==============================================================================

# [1-1] 기본 DataFrame 생성
# > 0, 1, 2... 정수형 인덱스가 자동 부여됨
print(f"\n{'=' * 50}\n[1-1] 기본 DataFrame 형태\n")
df = pd.DataFrame(data)
print(df)


# [1-2] 이름 컬럼을 인덱스로 변경
print(f"\n{'-' * 50}\n[1-2] '이름' 컬럼을 행 인덱스로 지정: df.set_index('이름')\n")

df_indexed = df.set_index("이름") # > 기본 숫자 라벨(0, 1, 2...) 대신 '이름' 컬럼의 데이터들을 행의 라벨(Label)로 변경 (loc 접근 시 사용)
print(df_indexed)


# ==============================================================================
# 2. 라벨 기반 행 선택 (loc)
# ==============================================================================

# [2-1] 범위 슬라이싱
# > 주의: loc 슬라이싱은 기본 숫자 인덱스(0, 1, 2...)여도 '끝 라벨'을 반드시 포함 (iloc는 미포함)

print(f"\n{'=' * 50}\n2. 인덱스 기반 행 선택: df.loc\n\n[실행] df.loc['이영희':'정소희'] (이영희부터 정소희까지 포함)\n")
print(df_indexed.loc["이영희":"정소희"]) # > 이름 컬럼을 인덱스로 설정했기에 문자열 이름값으로 슬라이싱 가능


# ==============================================================================
# 3. 위치 기반 선택 (iloc: index location, integer location)
# ==============================================================================

# [3-1] 단일 행 선택 (Series 반환)
# > 인덱스 라벨 명칭과 무관하게 0부터 시작하는 실제 위치(정수 오프셋)로 추출

print(f"\n{'=' * 50}\n3. 위치 기반 행 선택: df.iloc (정수 인덱스)\n\n[실행] df.iloc[1] (1개 행 추출 -> Series 반환)\n")
print(df_indexed.iloc[1])


# [3-2] 여러 행 선택 (DataFrame 반환)

print(f"\n[실행] df.iloc[[1, 3]] (1번, 3번 행 추출 -> DataFrame 반환)\n")
print(df_indexed.iloc[[1, 3]]) # > 리스트 형태로 정수 번호를 전달하여 복수 행 추출



# ==============================================================================
# 4. 조건 기반 선택
# ==============================================================================

print(f"\n{'=' * 50}\n4. 조건 기반 선택 \n")


# 첫번째와 세번째만 가져옴
print("\n[실행] df.loc[[True, False, True, False, False]]\n")

print(df.loc[[True, False, True, False, False]]) # 들어가는 인자의 수는 레코드 개수와 동일해야함


# 4.0 이상인지 여부(True/False)로 이루어진 시리즈 생성
print("\n[실행] df[\"학점\"] >= 4.0\n")

high_score = df["학점"] >= 4.0  # 단일 True/ False 값이 아닌 여러 값이 나옴
print(high_score)


# loc에 조건 넣기
print("\n[실행] df.loc[df[\"학점\"]]\n")
print(df.loc[high_score])

# df[] 안에 조건 넣기
df[df["학년"] == 2]

df[(df["학년"] == 2) & (df["학점"]>= 3.7)]

==================================================
[1-1] 기본 DataFrame 형태

    이름  학년   학점     학과    동아리
0  김철수   1  4.2  컴퓨터공학  프로그래밍
1  이영희   2  3.8    경영학   독서토론
2  박민수   3  4.5   전자공학   로봇공학
3  최지훈   4  3.9     의학   봉사활동
4  정소희   2  3.5    심리학   음악감상

--------------------------------------------------
[1-2] '이름' 컬럼을 행 인덱스로 지정: df.set_index('이름')

     학년   학점     학과    동아리
이름
김철수   1  4.2  컴퓨터공학  프로그래밍
이영희   2  3.8    경영학   독서토론
박민수   3  4.5   전자공학   로봇공학
최지훈   4  3.9     의학   봉사활동
정소희   2  3.5    심리학   음악감상

==================================================
2. 인덱스 기반 행 선택: df.loc

[실행] df.loc['이영희':'정소희'] (이영희부터 정소희까지 포함)

     학년   학점    학과   동아리
이름
이영희   2  3.8   경영학  독서토론
박민수   3  4.5  전자공학  로봇공학
최지훈   4  3.9    의학  봉사활동
정소희   2  3.5   심리학  음악감상

==================================================
3. 위치 기반 행 선택: df.iloc (정수 인덱스)

[실행] df.iloc[1] (1개 행 추출 -> Series 반환)

학년        2
학점      3.8
학과      경영학
동아리    독서토론
Name: 이영희, dtype: object

[실행] df.iloc[[1, 3]] (1번, 3번 행 추출 -> DataFrame 반환)

     학년   학점   학과   동아리
이름
이영희   2  3.8  경영학  독서토론
최지훈   4  3.9   의학  봉사활동

==================================================
4. 조건 기반 선택


[실행] df.loc[[True, False, True, False, False]]

    이름  학년   학점     학과    동아리
0  김철수   1  4.2  컴퓨터공학  프로그래밍
2  박민수   3  4.5   전자공학   로봇공학

[실행] df["학점"] >= 4.0

0     True
1    False
2     True
3    False
4    False
Name: 학점, dtype: bool

[실행] df.loc[df["학점"]]

    이름  학년   학점     학과    동아리
0  김철수   1  4.2  컴퓨터공학  프로그래밍
2  박민수   3  4.5   전자공학   로봇공학

    이름  학년   학점   학과   동아리
1  이영희   2  3.8  경영학  독서토론

### 6-4 DataFrame 정렬

In [75]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

#DataFrame 인덱스 지정
df = pd.DataFrame(data).set_index("이름")
print("[이름을 인덱스로 지정한 결과]\n", df, end="\n\n")


#DataFrame 단일 열 오름차순, 내림차순 정렬
df.sort_values(by="학점") # 오름차순 (기본 설정)
df.sort_values(by="학점", ascending= False) # ascending= False -> 내림차순

#DataFrame 복수 열 오름차순, 내림차순 정렬
df.sort_values(by=["학년", "학점"], ascending= [True, False]) # 학년 오름차순, 학점 내림차순으로 정렬


#DataFrame 인덱스 기준 오른차순, 내림차순 정렬
index_sorted = df.sort_index(ascending= False)
print("[인덱스 기준 정렬 - 이름 순 내림차순 정렬]\n",index_sorted)

[이름을 인덱스로 지정한 결과]
      학년   학점     학과    동아리
이름
김철수   1  4.2  컴퓨터공학  프로그래밍
이영희   2  3.8    경영학   독서토론
박민수   3  4.5   전자공학   로봇공학
최지훈   4  3.9     의학   봉사활동
정소희   2  3.5    심리학   음악감상

[인덱스 기준 정렬 - 이름 순 내림차순 정렬]
      학년   학점     학과    동아리
이름
최지훈   4  3.9     의학   봉사활동
정소희   2  3.5    심리학   음악감상
이영희   2  3.8    경영학   독서토론
박민수   3  4.5   전자공학   로봇공학
김철수   1  4.2  컴퓨터공학  프로그래밍

## 6-5 실습 시나리오 - Kaggle을 활용한 데이터 수집 및 측정

- Kaggle([https://www.kaggle.com](https://www.kaggle.com)) 회원 가입
- Kaggle 접근 토큰 생성(API 키)

### Kaggle API 키 업로드

다운받은 kaggle.json 파일 업로드

In [82]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle (1).json

{'kaggle (1).json': b'{"username":"wolivine29wolivine29","key":"4978b90e41e04034587f37450296c5f7"}'}

실행결과로 노출 된 api키는 만료시켰음

### Kaggle API 키 사용을 위한 Colab 환경 설정

In [83]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

### Kaggle 데이터셋 다운로드

In [88]:
!kaggle competitions download -c store-sales-time-series-forecasting

!unzip store-sales-time-series-forecasting.zip

Downloading store-sales-time-series-forecasting.zip to /content
100% 21.4M/21.4M [00:00<00:00, 113MB/s]

Archive:  store-sales-time-series-forecasting.zip
  inflating: holidays_events.csv
  inflating: oil.csv
  inflating: sample_submission.csv
  inflating: stores.csv
  inflating: test.csv
  inflating: train.csv
  inflating: transactions.csv

### Kaggle 데이터셋 DataFrame 로드 및 살펴보기

In [89]:
import pandas as pd

# Grocery Sales 데이터 DataFrame 로드
train = pd.read_csv('train.csv')
stores = pd.read_csv('stores.csv')
transactions = pd.read_csv('transactions.csv')
oil = pd.read_csv('oil.csv')
holidays_events = pd.read_csv('holidays_events.csv')

# 판매 데이터 살펴보기
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   date         object
 2   store_nbr    int64
 3   family       object
 4   sales        float64
 5   onpromotion  int64
dtypes: float64(1), int64(3), object(2)
memory usage: 137.4+ MB

### Kaggle 데이터셋 측정

In [92]:
# 판매 데이터 기본 통계량
print(train.describe(), end="\n\n")

# 매장 데이터 기본 정보
print(stores.head(), end="\n\n")

# 원유 가격 데이터 기본 정보
print(oil.head(), end="\n\n")

                 id     store_nbr         sales   onpromotion
count  3.000888e+06  3.000888e+06  3.000888e+06  3.000888e+06
mean   1.500444e+06  2.750000e+01  3.577757e+02  2.602770e+00
std    8.662819e+05  1.558579e+01  1.101998e+03  1.221888e+01
min    0.000000e+00  1.000000e+00  0.000000e+00  0.000000e+00
25%    7.502218e+05  1.400000e+01  0.000000e+00  0.000000e+00
50%    1.500444e+06  2.750000e+01  1.100000e+01  0.000000e+00
75%    2.250665e+06  4.100000e+01  1.958473e+02  0.000000e+00
max    3.000887e+06  5.400000e+01  1.247170e+05  7.410000e+02

   store_nbr           city                           state type  cluster
0          1          Quito                       Pichincha    D       13
1          2          Quito                       Pichincha    D       13
2          3          Quito                       Pichincha    D        8
3          4          Quito                       Pichincha    D        9
4          5  Santo Domingo  Santo Domingo de los Tsachilas    D        4

         date  dcoilwtico
0  2013-01-01         NaN
1  2013-01-02       93.14
2  2013-01-03       92.97
3  2013-01-04       93.12
4  2013-01-07       93.20